#!/usr/bin/env python3
"""Build a runtime-oriented system health YAML from expected contract + snapshots.

Typical usage:
1) Robot stack is running.
2) Run this script to capture runtime graph and merge with expected launch extraction.
3) Use the generated YAML as config_file for system_health_monitor.
"""

from __future__ import annotations

import argparse
import copy
import datetime as dt
import re
import subprocess
from pathlib import Path
from typing import Any

import yaml


DEFAULT_BASE_DIR = Path.home() / "system_health"
DEFAULT_OUTPUT_PATH = DEFAULT_BASE_DIR / "system_health_real_robot.yaml"
DEFAULT_SNAPSHOT_DIR = DEFAULT_BASE_DIR / "snapshots"


IGNORED_TOPICS = {
    "/parameter_events",
    "/rosout",
}

# Noise service suffixes automatically generated by node parameters API.
IGNORED_SERVICE_SUFFIXES = (
    "/describe_parameters",
    "/get_parameter_types",
    "/get_parameters",
    "/list_parameters",
    "/set_parameters",
    "/set_parameters_atomically",
)

IGNORED_NODE_PREFIXES = (
    "/_",
    "/system_health_cli",
)


def normalize_name(name: str) -> str:
    name = (name or "").strip()
    if not name:
        return name
    if not name.startswith("/"):
        name = "/" + name
    return name


def is_dynamic_name(name: str) -> bool:
    return "<dynamic:" in (name or "")


def safe_load_yaml(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"Expected YAML dict at root, got: {type(data).__name__}")
    return data


def split_types(raw: str) -> list[str]:
    text = (raw or "").strip()
    if not text:
        return []
    # Handles single type and comma-separated lists.
    return [x.strip() for x in text.split(",") if x.strip()]


def is_system_node(name: str) -> bool:
    return any(name.startswith(prefix) for prefix in IGNORED_NODE_PREFIXES)


def is_system_topic(name: str) -> bool:
    return name in IGNORED_TOPICS


def parse_nodes_file(path: Path, include_system_nodes: bool = False) -> set[str]:
    nodes: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or not line.startswith("/"):
            continue
        name = normalize_name(line.split()[0])
        if not include_system_nodes and is_system_node(name):
            continue
        nodes.add(name)
    return nodes


LINE_WITH_TYPES_RE = re.compile(r"^(?P<name>\S+)\s+\[(?P<types>.*)\]\s*$")


def parse_name_types_file(path: Path, ignored_names: set[str] | None = None) -> dict[str, list[str]]:
    ignored_names = ignored_names or set()
    out: dict[str, list[str]] = {}

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or not line.startswith("/"):
            continue
        m = LINE_WITH_TYPES_RE.match(line)
        if m:
            name = normalize_name(m.group("name"))
            types = split_types(m.group("types"))
        else:
            # Fallback if line has no "[type]".
            name = normalize_name(line.split()[0])
            types = []

        if name in ignored_names:
            continue
        out[name] = sorted(set(types))
    return out


def should_ignore_service(name: str) -> bool:
    if name.startswith("/_"):
        return True
    return any(name.endswith(suffix) for suffix in IGNORED_SERVICE_SUFFIXES)


def parse_services_file(path: Path, include_system_services: bool = False) -> dict[str, list[str]]:
    raw = parse_name_types_file(path)
    out: dict[str, list[str]] = {}
    for name, types in raw.items():
        if not include_system_services and should_ignore_service(name):
            continue
        out[name] = types
    return out


def parse_topics_file(path: Path, include_system_topics: bool = False) -> dict[str, list[str]]:
    if include_system_topics:
        return parse_name_types_file(path)
    return parse_name_types_file(path, ignored_names=IGNORED_TOPICS)


def maybe_capture_runtime(
    capture: bool,
    snapshot_dir: Path,
    nodes_file: Path | None,
    topics_file: Path | None,
    services_file: Path | None,
) -> tuple[Path, Path, Path]:
    if not capture:
        if nodes_file is None or topics_file is None or services_file is None:
            raise ValueError(
                "Without --capture you must provide --nodes-file, --topics-file and --services-file."
            )
        return nodes_file, topics_file, services_file

    snapshot_dir.mkdir(parents=True, exist_ok=True)
    stamp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    nodes_path = snapshot_dir / f"nodes_{stamp}.txt"
    topics_path = snapshot_dir / f"topics_{stamp}.txt"
    services_path = snapshot_dir / f"services_{stamp}.txt"

    def run_cmd(cmd: list[str]) -> str:
        result = subprocess.run(cmd, check=True, text=True, capture_output=True)
        return result.stdout

    nodes_path.write_text(run_cmd(["ros2", "node", "list"]), encoding="utf-8")
    topics_path.write_text(run_cmd(["ros2", "topic", "list", "-t"]), encoding="utf-8")
    services_path.write_text(run_cmd(["ros2", "service", "list", "-t"]), encoding="utf-8")
    return nodes_path, topics_path, services_path


def merge_types(existing: list[str], runtime: list[str]) -> list[str]:
    merged = []
    seen = set()
    for val in (existing or []) + (runtime or []):
        text = str(val).strip()
        if not text:
            continue
        if text in seen:
            continue
        seen.add(text)
        merged.append(text)
    return merged


def build_nodes(
    expected_nodes: list[dict[str, Any]],
    runtime_nodes: set[str],
    include_runtime_only: bool,
) -> list[dict[str, Any]]:
    by_name: dict[str, dict[str, Any]] = {}
    for item in expected_nodes:
        if not isinstance(item, dict):
            continue
        name = normalize_name(str(item.get("name", "")))
        if not name:
            continue
        if is_dynamic_name(name):
            continue
        row = copy.deepcopy(item)
        row["name"] = name
        row["runtime_observed"] = name in runtime_nodes
        if "critical" not in row:
            row["critical"] = False
        by_name[name] = row

    if include_runtime_only:
        for name in sorted(runtime_nodes):
            if name in by_name:
                continue
            by_name[name] = {
                "name": name,
                "critical": False,
                "condition": "runtime_only",
                "runtime_observed": True,
                "note": "Observed in runtime snapshot but missing from expected launch extraction.",
            }

    return sorted(by_name.values(), key=lambda x: x.get("name", ""))


def build_topics(
    expected_topics: list[dict[str, Any]],
    runtime_topics: dict[str, list[str]],
    include_runtime_only: bool,
) -> list[dict[str, Any]]:
    by_name: dict[str, dict[str, Any]] = {}
    for item in expected_topics:
        if not isinstance(item, dict):
            continue
        name = normalize_name(str(item.get("name", "")))
        if not name:
            continue
        if is_dynamic_name(name):
            continue
        runtime_types = runtime_topics.get(name, [])
        row = copy.deepcopy(item)
        row["name"] = name
        row["types"] = merge_types(list(row.get("types") or []), runtime_types)
        row["runtime_observed"] = name in runtime_topics
        row.setdefault("critical", False)
        row.setdefault("min_rate_hz", None)
        row.setdefault("max_age_sec", None)
        row.setdefault("expected_publishers", [])
        row.setdefault("expected_subscribers", [])
        row.setdefault("externally_provided", False)
        by_name[name] = row

    if include_runtime_only:
        for name, types in sorted(runtime_topics.items()):
            if name in by_name:
                continue
            by_name[name] = {
                "name": name,
                "critical": False,
                "min_rate_hz": None,
                "max_age_sec": None,
                "types": types,
                "expected_publishers": [],
                "expected_subscribers": [],
                "externally_provided": True,
                "runtime_observed": True,
                "condition": "runtime_only",
            }

    return sorted(by_name.values(), key=lambda x: x.get("name", ""))


def build_services(
    expected_services: list[dict[str, Any]],
    runtime_services: dict[str, list[str]],
    include_runtime_only: bool,
) -> list[dict[str, Any]]:
    by_name: dict[str, dict[str, Any]] = {}
    for item in expected_services:
        if not isinstance(item, dict):
            continue
        name = normalize_name(str(item.get("name", "")))
        if not name:
            continue
        if is_dynamic_name(name):
            continue
        runtime_types = runtime_services.get(name, [])
        row = copy.deepcopy(item)
        row["name"] = name
        row["types"] = merge_types(list(row.get("types") or []), runtime_types)
        row["runtime_observed"] = name in runtime_services
        row.setdefault("critical", False)
        row.setdefault("timeout_sec", 1.0)
        row.setdefault("expected_servers", [])
        row.setdefault("expected_clients", [])
        row.setdefault("externally_provided", False)
        row.setdefault("probe_call", False)
        row.setdefault("probe_timeout_sec", None)
        row.setdefault("probe_interval_sec", None)
        row.setdefault("probe_request", {})
        by_name[name] = row

    if include_runtime_only:
        for name, types in sorted(runtime_services.items()):
            if name in by_name:
                continue
            by_name[name] = {
                "name": name,
                "critical": False,
                "timeout_sec": 1.0,
                "types": types,
                "expected_servers": [],
                "expected_clients": [],
                "externally_provided": True,
                "runtime_observed": True,
                "condition": "runtime_only",
                "probe_call": False,
                "probe_timeout_sec": None,
                "probe_interval_sec": None,
                "probe_request": {},
            }

    return sorted(by_name.values(), key=lambda x: x.get("name", ""))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge expected launch extraction with runtime ROS2 snapshot into final health YAML."
    )
    parser.add_argument(
        "--expected",
        type=Path,
        default=None,
        help="Path to *_expected.yaml generated from extract_expected_system.py. If omitted, auto-detect is used.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help=f"Output YAML path (default: {DEFAULT_OUTPUT_PATH})",
    )
    parser.add_argument(
        "--scenario",
        type=str,
        default="real_robot",
        help="Scenario label in output YAML (default: real_robot)",
    )
    parser.add_argument(
        "--snapshot-dir",
        type=Path,
        default=DEFAULT_SNAPSHOT_DIR,
        help=f"Directory for snapshot files (and capture output when --capture is used). Default: {DEFAULT_SNAPSHOT_DIR}",
    )
    parser.add_argument("--nodes-file", type=Path, default=None, help="nodes_*.txt file")
    parser.add_argument("--topics-file", type=Path, default=None, help="topics_*.txt file")
    parser.add_argument("--services-file", type=Path, default=None, help="services_*.txt file")
    parser.add_argument(
        "--capture",
        action="store_true",
        help="Capture current runtime graph using ros2 CLI instead of requiring snapshot files.",
    )
    parser.add_argument(
        "--no-runtime-only",
        action="store_true",
        help="Do not include runtime-only entries that are not present in expected YAML.",
    )
    parser.add_argument(
        "--include-system-interfaces",
        action="store_true",
        help="Include system ROS interfaces (/rosout, /parameter_events, parameter services, etc.) in runtime checks.",
    )
    return parser.parse_args()


def resolve(base: Path, path: Path | None) -> Path | None:
    if path is None:
        return None
    return path if path.is_absolute() else (base / path)


def autodetect_expected(cwd: Path) -> Path | None:
    direct_candidates = [
        DEFAULT_BASE_DIR / "expected.yaml",
    ]
    for p in direct_candidates:
        if p.exists():
            return p

    patterns = [
        DEFAULT_BASE_DIR.glob("*_expected.yaml"),
        (cwd / "files" / "system_health").glob("*_expected.yaml"),
        cwd.glob("*_expected.yaml"),
    ]
    found: list[Path] = []
    for group in patterns:
        found.extend([p for p in group if p.is_file()])
    if not found:
        return None
    found.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return found[0]


def main() -> int:
    args = parse_args()
    cwd = Path.cwd()

    expected_path = resolve(cwd, args.expected)
    if expected_path is None:
        expected_path = autodetect_expected(cwd)
    output_path = resolve(cwd, args.output)
    snapshot_dir = resolve(cwd, args.snapshot_dir)
    nodes_file = resolve(cwd, args.nodes_file)
    topics_file = resolve(cwd, args.topics_file)
    services_file = resolve(cwd, args.services_file)

    if expected_path is None:
        raise SystemExit(
            "Expected YAML was not provided and auto-detect failed. "
            "Pass --expected /path/to/*_expected.yaml or place one under ~/system_health/."
        )
    if not expected_path.exists():
        raise SystemExit(f"Expected YAML not found: {expected_path}")

    nodes_file, topics_file, services_file = maybe_capture_runtime(
        capture=args.capture,
        snapshot_dir=snapshot_dir,
        nodes_file=nodes_file,
        topics_file=topics_file,
        services_file=services_file,
    )

    for file_path in (nodes_file, topics_file, services_file):
        if not file_path.exists():
            raise SystemExit(f"Snapshot file not found: {file_path}")

    expected = safe_load_yaml(expected_path)
    health = expected.get("health_template", {}) or {}
    expected_nodes = health.get("nodes", []) or []
    expected_topics = health.get("topics", []) or []
    expected_services = health.get("services", []) or []

    runtime_nodes = parse_nodes_file(nodes_file, include_system_nodes=args.include_system_interfaces)
    runtime_topics = parse_topics_file(topics_file, include_system_topics=args.include_system_interfaces)
    runtime_services = parse_services_file(services_file, include_system_services=args.include_system_interfaces)

    include_runtime_only = not args.no_runtime_only
    final_yaml = {
        "version": 1,
        "scenario": args.scenario,
        "description": (
            "Auto-generated from expected launch extraction and runtime ROS2 snapshot. "
            "Review critical flags per mission profile."
        ),
        "meta": {
            "generated_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
            "source_expected_yaml": str(expected_path),
            "source_nodes_file": str(nodes_file),
            "source_topics_file": str(topics_file),
            "source_services_file": str(services_file),
            "include_runtime_only": include_runtime_only,
            "include_system_interfaces": args.include_system_interfaces,
            "notes": [
                "Runtime-only entries often include bridge-provided interfaces or external systems.",
                "Parameter services and rosout/parameter_events are filtered by default unless --include-system-interfaces is set.",
                "Treat critical flags as operational policy and tune them per scenario.",
            ],
        },
        "health_template": {
            "nodes": build_nodes(expected_nodes, runtime_nodes, include_runtime_only),
            "topics": build_topics(expected_topics, runtime_topics, include_runtime_only),
            "services": build_services(expected_services, runtime_services, include_runtime_only),
        },
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    yaml_text = yaml.safe_dump(final_yaml, sort_keys=False, allow_unicode=False)
    output_path.write_text(yaml_text, encoding="utf-8")

    print(f"[ok] generated: {output_path}")
    print(f"      expected: {expected_path}")
    print(f"      nodes:    {len(final_yaml['health_template']['nodes'])}")
    print(f"      topics:   {len(final_yaml['health_template']['topics'])}")
    print(f"      services: {len(final_yaml['health_template']['services'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
